config/routes.rb
Rails.application.routes.draw do
  resources :matchers, only: [:index]
  post 'cfpb_lookup', to: 'matchers#cfpb_lookup', as: 'cfpb_lookup'
  post 'exact_lookup', to: 'matchers#exact_lookup', as: 'exact_lookup'

  root 'matchers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matchers_controller.rb
class MatchersController < ApplicationController
  def index; end

  def cfpb_lookup
    api_response = CompanyLookupService.new.lookup params[:company_name]
    @company_match = process_cfpb_lookup_response api_response

    respond_to { |format| format.js }
  end

  def exact_lookup
    api_responses = CompanyLookupService.new.pull_company params[:cfpb_name],
                                                          params[:iex_name]
    @api_responses = process_exact_lookup_response api_responses

    respond_to { |format| format.js }
  end

  private

  def process_cfpb_lookup_response(api_response)
    if api_response[:cfpb].blank?
      api_response.merge error: 'No company in the CFPB with a name like that.'
    elsif api_response[:iex].blank?
      api_response.merge error: 'We found a CFPB complaint, but could not ' \
                                'find a publicly traded stock associated with' \
                                ' that company.'
    else
      api_response
    end
  end

  def process_exact_lookup_response(api_responses)
    if api_responses[:iex]['companyName'].blank? || api_responses[:cfpb_random_complaint].blank?
      api_responses.merge error: 'ERROR'
    else
      api_responses
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matchers_helper.rb
module MatchersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CFPB vs IEX</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>    
    </div>
  </body>
</html>

app/views/matchers/_cfpb_lookup_form.html.erb
<%= bootstrap_form_tag url: cfpb_lookup_path, remote: true do |f| %>
  <%= f.text_field :company_name, help: 'Company name. e.g. Bank of America, Toyota' %>
  <%= f.submit 'Look up company in CFPB complaint', class: 'btn btn-primary' %>
<% end %>

app/views/matchers/_exact_lookup_form.html.erb
<% if company_match[:error] %>
  <div class="row errors">
    <p class="text-danger">
      <%= company_match[:error] %> Sorry! Give it another shot?    
    </p>
  </div>
<% else %>
  <div class="row">
    <p class='text-success'>
      Looks like we have a match! Does that look okay to you?
    </p>
  </div>
  <div class="row">
    <%= bootstrap_form_tag url: exact_lookup_path, remote: true do |f| %>
      <%= f.text_field :cfpb_name, value: company_match[:cfpb], label: 'CFPB company name' %>
      <%= f.text_field :iex_name, value: company_match[:iex], label: 'IEX company name' %>
      <%= f.submit 'Yep, look it up', class: 'btn btn-success' %>
    <% end %>    
  </div>
<% end %>

app/views/matchers/_result.html.erb
<% if api_responses[:error] %>
  Sorry, something screwed up!
<% else %>
  <div class="col-md-6">
    <h3>Found <%= api_responses[:cfpb_complaint_count] %> CFPB complaints for <%= api_responses[:cfpb_random_complaint]['company'].titleize %></h3>

    <p><%= api_responses[:cfpb_random_complaint]['complaint_what_happened'] %></p>
  </div>

  <div class="col-md-6">
    <h3><%= api_responses[:iex]['companyName'] %> stock values<h3>

    <p><%= number_to_currency api_responses[:iex]['latestPrice'] %> (high of <%= number_to_currency api_responses[:iex]['high'] %>)</p>
  </div>
<% end %>

app/views/matchers/cfpb_lookup.js.erb
$('#exact_form').empty().append('<%= escape_javascript(render partial: "matchers/exact_lookup_form", locals: { company_match: @company_match }) %>');

app/views/matchers/exact_lookup.js.erb
$('#results').empty().append('<%= escape_javascript(render partial: "matchers/result", locals: { api_responses: @api_responses }) %>');

app/views/matchers/index.html.erb
<div class="jumbotron" id="header">
  <h1>CFPB Complaint vs IEX Stock Price</h1>
  <p>Compare a company's Consumer Financial Protection Bureau complaints vs current stock prices, according to IEX.</p>
</div>

<div class="row">
  <div class="col-md-6" id="cfpb_form">
    <%= render 'cfpb_lookup_form' %>
  </div>

  <div class="col-md-6" id='exact_form'></div>
</div>

<div id="results"></div>